### ISSUE TITLE
ProductAPI  fails with SKUs containing '/' 

### ISSUE THREAD

**Issue by chrishodgsonplt** [akeneo/api-php-client#124]
When trying to find a product using the Akeneo API Client (ProductAPI) it cannot handle product SKUs containing '/'. It confuses the slashes for part of the route

`$client->getProductApi()->get('SKU/WITH/SLASHES');`

`request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /api/rest/v1/products/SKU/WITH/SLASHES""`

**Comment by ahocquard** [comment]
It seems that this problem is coming from the PIM and not for the client itself.
Therefore, I close this ticket but feel free to re-open it if it's really coming from the PHP client.
