### ISSUE TITLE
Issue with "with_count" in conjunction with ListableResourceInterface

### ISSUE THREAD

**Issue by Toflar** [akeneo/api-php-client#130]
Hey everybody,

I'm trying to get all categories and include their count. Unfortunately, that's not possible right now because the `CategoryApi` does not support passing the `$withCount` variable in `all()`. I understand that's an issue there because `all()` is part of the `ListableResourceInterface` so you cannot adjust that without breaking BC.

However, why is it not allowed to pass `['with_count' => true]`? It should work pretty straight forward by doing the following:

```diff
    /**
     * {@inheritdoc}
     */
    public function all($pageSize = 10, array $queryParameters = [])
    {
+        $withCount = false;
+
+        if (array_key_exists('with_count', $queryParameters)) {
+            $withCount = (bool) $queryParameters['with_count'];
+            unset($queryParameters['with_count']);
+        }

+        $firstPage = $this->listPerPage($pageSize, $withCount, $queryParameters);
-        $firstPage = $this->listPerPage($pageSize, false, $queryParameters);

        return $this->cursorFactory->createCursor($pageSize, $firstPage);
    }
```

**Comment by Toflar** [comment]
Any feedback on this? I'll happily work on a PR but I want to get some feedback on the concept :)

**Comment by Toflar** [comment]
Thanks for the reply but I don't think you understood the issue exactly :-) As far as I understood from the API docs (https://api.akeneo.com/api-reference-21.html#get_categories), the `with_count` parameter adds the number of products per category to the result. It's not related to pagination or the cursor at all, is it? 

What I need is the number of products per category so I can build something like this:

* Category A (512)
  * Category C (18)
  * Category D (494)
* Category B (32)

**Comment by ahocquard** [comment]
Hello,

No, this count is the total number of categories.

If you want to get the number of products in a category, you have to request the product endpoint with a filter `IN CHILDREN`:
https://api.akeneo.com/documentation/filter.html#on-categories

It's not possible to do it in 1 request.

**Comment by Toflar** [comment]
Ah, I see. Thank you for taking the time to reply then 👍
