### ISSUE TITLE
Can't install via Composer (php-http/guzzle6-adapter upgraded)

### ISSUE THREAD

**Issue by element-code** [akeneo/api-php-client#148]
Hi,

currently you require `php-http/httplug` in your pakage and suggest `php-http/guzzle6-adapter`. This wont work anymore because they upgraded to `2.0.0`. Please suggest `php-http/guzzle6-adapter ^1.0.0` instead!

thanks :)

----
**why it won't work:**
`php-http/guzzle6-adapter` itself requires `php-http/httplug`. Since [guzzle6-adapter@de1ebb7](https://github.com/php-http/guzzle6-adapter/commit/de1ebb7b8b3a8d2681b7b4e276cf789052942564) they require version `^2.0` which creates a conflict with your version `^1.0` requirement.

**Comment by tomglvng** [comment]
Hello @element-code,

Thank you for your suggestion,

I just checked our composer.json and we use php-http/guzzle6-adapter ^2.0.

I close the issue.

Regards,

The Akeneo development team,
