### ISSUE TITLE
incorrect information in the API guide for getAttributeOptionsApi()->upsertList() 

### ISSUE THREAD

**Issue by johamm** [akeneo/api-php-client#175]
I think there's a small mistake in the API documentation for upserting a list of options into an attribute:

https://api.akeneo.com/php-client/resources.html#upsert-a-list-of-attribute-options

When you look at the code, it's actually expecting the attribute code as the first parameter of the upsertList() call.

**Comment by jmleroux** [comment]
Hello @johamm 

Thank you for raising this issue, I will check with API team to fix this error.
Unless you want to make a PR :wink: 

Regards,
JM

**Comment by johamm** [comment]
hahah thanks for that! I'm happy just reporting it lol :)

**Comment by DRN88** [comment]
Same issue here.

**Comment by timonburkard** [comment]
still incorrect. see also: https://github.com/akeneo/api-php-client-ee/issues/99
