### ISSUE TITLE
Delete Products or Attributes (for test purposes)

### ISSUE THREAD

**Issue by heojee1** [akeneo/api-php-client#181]
Our team is trying to test a script that imports products (and catalog structure entities) into Akeneo. Is there an efficient or standard way to do this?

Our idea now is to test with a test DB and delete all that has been created by the test. But we are not sure if there are any delete functions provided Akeneo PHP client.

**Comment by timonburkard** [comment]
@heojee1 Yes, you can delete a product with the Akeneo PHP client: https://api.akeneo.com/php-client/resources.html#delete-a-product
