### ISSUE TITLE
Consider updating PHPSpec package

### ISSUE THREAD

**Issue by peter279k** [akeneo/api-php-client#182]
As title, it will be failed on `php-7.4` version when `phpspec` is `^5.0` version.

The related issue is available [here](https://github.com/phpspec/phpspec/issues/1274).

And it should be good for `php-7.4` version uses `phpspec` `^6.0` version.

To resolve this issue, I think we have two different ways:

- Defining two `phpspec` version with `^5.0 || ^6.0` inside `require` block on `composer.json`.
And using the `composer update --prefer-dist --no-interaction` during Travis CI build.
- Removing `composer.lock` and define two `phpspec` version with `^5.0 || ^6.0` inside `require` block on `composer.json`.

**Comment by tomglvng** [comment]
Hello @peter279k,

Thanks for your suggestion. We just tagged a new version of our client with PHP 7.4 and PHPSpec 7.1.
see https://github.com/akeneo/api-php-client/commit/c43fdd43585053506177358bf90f6282232df7a7

Regards,

**Comment by peter279k** [comment]
Thanks. And it will be resolved now :).
