### ISSUE TITLE
how to get units

### ISSUE THREAD

**Issue by snabi** [akeneo/api-php-client#183]
I cannot see units in the api from PIM

**Comment by timonburkard** [comment]
What exactly are you trying to do? Are you trying to get a list of all available units? Or are you trying to get the unit for a specific product value?

Getting all the units could be done as follows:
```php
// Get metric units
$aMetricUnits = [];
foreach($api->getMeasureFamilyApi()->all() as $aMeasureFamily)
{
    foreach($aMeasureFamily['units'] as $unit)
    {
        $aMetricUnits[$aMeasureFamily['code']][] = $unit;
    }
}
```
