### ISSUE TITLE
Operator between filters for the search builder

### ISSUE THREAD

**Issue by samspinoy** [akeneo/api-php-client#187]
Is there a possibility to specify the operator between filters when searching for products? 

F.ex. if I have the search query "product title 123-456-789", I would like to search both product title and identifier for this string. If **either one** of those fields contains (part of) the search string it should be returned. Currently, by using the addFilter() method, I can only get products that contain (part of) this search string in **both** fields.

Since elastic search is used as underlying technology, this should surely be possible?

**Comment by timonburkard** [comment]
Basically you are asking for a possibility to add the OR condition for filters, right? I'd like that too!

**Comment by LevFlavien** [comment]
Hi @samspinoy @timonburkard,

"OR" operator for filters is not supported in the PIM API. As far as I know, it is not a planned feature.
So I'm closing the issue. If feel like discussing this feature, the most appropriate place would be the PIM project https://github.com/akeneo/pim-community-dev

Regards,

Akeneo dev team
