### ISSUE TITLE
Matrix compatibility out of date?

### ISSUE THREAD

**Issue by grena** [akeneo/api-php-client#191]
Hello Akeneo!

It seems the README.md is out of date regarding the matrix compatibility available here: https://api.akeneo.com/php-client/introduction.html

![Screenshot_2020-11-19 PHP API client documentation](https://user-images.githubusercontent.com/301169/99689920-d6f0f800-2a87-11eb-90bc-2467e098c31e.png)

On this repo:
![Screenshot_2020-11-19 akeneo api-php-client](https://user-images.githubusercontent.com/301169/99689963-e2dcba00-2a87-11eb-860c-b00c7a226d65.png)

This is quite misleading, I think this could be updated. Thanks for your reading!

**Comment by tomglvng** [comment]
Hello @grena,

We just updated it! See https://github.com/akeneo/api-php-client/commit/e35b6892970a4604c232080cf82d06e9c5779b6c

Regards,
