### ISSUE TITLE
Reference Entities

### ISSUE THREAD

**Issue by davist11** [akeneo/api-php-client#192]
Is there any plan to add the functionality to access [Reference Entities](https://api.akeneo.com/api-reference-index.html#Referenceentities)?

**Comment by JeroenVanLeusden** [comment]
We're also interested in using these endpoints.

**Comment by davist11** [comment]
I tracked down that this is actually available, but you have to use the enterprise edition client: https://github.com/akeneo/api-php-client-ee/blob/master/src/Api/ReferenceEntityApi.php

**Comment by PascalBrouwers** [comment]
https://github.com/akeneo/api-php-client/blob/master/src/Api/ReferenceEntityApi.php
Added since november 2022
