### ISSUE TITLE
Operators for filters to search resources incomplete

### ISSUE THREAD

**Issue by wucherpfennig** [akeneo/api-php-client#199]
Dear all

I have noticed that the operators are incomplete. Missing are the ones for completeness filtering on models.

https://api.akeneo.com/documentation/filter.html#on-completeness

BR wucherpfennig

**Comment by tomglvng** [comment]
Hi @wucherpfennig,

**Comment by LevFlavien** [comment]
Hi @wucherpfennig 

You should be able to make it work like this:
```php
$searchBuilder = new \Akeneo\Pim\ApiClient\Search\SearchBuilder();

// Third argument $value must be left null.
$searchBuilder->addFilter('completeness', 'ALL COMPLETE', null, ['locale' => 'en_US', 'scope' => 'ecommerce'])

$page = $client->getProductModelApi()->listPerPage(100, true, ['search' => $searchFilters]);
```
Although I agree there is room for improvement by making the call much more explicit, does it answers your initial comment?

**Comment by tomglvng** [comment]
Done in https://github.com/akeneo/api-php-client/pull/226.
Thanks again!
