### ISSUE TITLE
Filters doesn't work for categories.

### ISSUE THREAD

**Issue by vhrychenko** [akeneo/api-php-client#251]
I have the 4.0 version installed (CE) and if I try to filter categories by any rules it just ignores the ?search query param!

For products it works fine, but not for categories.

**Comment by LevFlavien** [comment]
H @vhrychenko 
What search filter are you trying to use?
Not all criteria are available in 4.0. Please refer to the filter documentation https://api.akeneo.com/documentation/filter.html#filter-categories

**Comment by LevFlavien** [comment]
No response, closing.
