### ISSUE TITLE
Suggested package php-http/guzzle6-adapter is deprecated

### ISSUE THREAD

**Issue by AngelinCalu** [akeneo/api-php-client#284]
The suggested package: [php-http/guzzle6-adapter](https://packagist.org/packages/php-http/guzzle6-adapter): 

> In order to use Guzzle v6 as the HTTP client 

has been abandoned. 

> This package is abandoned and no longer maintained. The author suggests using the guzzlehttp/guzzle or php-http/guzzle7-adapter package instead.
 
php-http/guzzle6-adapter requires [guzzlehttp/guzzle](https://packagist.org/packages/guzzlehttp/guzzle): ^6.0, however version 7^ is the major version adopted by most packages. 

Is the suggested package still relevant for the latest versions of `akeneo/api-php-client`? 
I can see it was there in the suggestions since early beta.

**Comment by tomglvng** [comment]
Done in https://github.com/akeneo/api-php-client/commit/f2ef753266c38a46ef36cdabb4a1f056af795de9
